apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-payment-pv-volume
spec:
  storageClassName: mongo-payment-storage
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
