apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-payment-pvc
spec:
  storageClassName: mongo-payment-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
